export const FETCH_AUTH_STATUS = "FETCH_AUTH_STATUS";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const POP_MESSAGE = "POP_MESSAGE";
